Repository devjeans-si-d/Si-D-client, pull requests merged in 2024-08, with the labels that each got.

#15 Feat/IS - 47 : 메인페이지 추가, Header컴포넌트 '회원가입'버튼 삭제
  src/components/header/HeaderComponent.vue
  src/components/windows/LaunchedProjectWindow.vue
  src/components/windows/ProjectWindow.vue
  src/components/windows/SiderCardWindow.vue
  src/router/LaunchedProjectRouter.js
  src/router/index.js
  src/views/LaunchedProject/LaunchedProjectList.vue
  src/views/LaunchedProject/LaunchedProjectRegister.vue
  src/views/MainPage/MainPage.vue
Labels: ✨ feature

#29 feat/IS-67: 마이페이지들 페이지네이션 구현, 화면 이동 코드 추가, "내 프로젝트" 페이지에 버튼 추가
  src/components/card/ChattingListComponent.vue
  src/components/card/EnChatroomComponent.vue
  src/components/card/EnChattingListComponent.vue
  src/components/card/ProjectApplyComponent.vue
  src/components/card/ProjectManagementComponent.vue
  src/components/card/ProjectScrapComponent.vue
  src/components/navbar/ApplyListBar.vue
  src/components/navbar/PageNavbar.vue
  src/components/navbar/ProjectSidebar.vue
  src/views/member/ChatroomView.vue
  src/views/member/ChattingList.vue
  src/views/member/MyApply.vue
  src/views/member/MyPage.vue
  src/views/member/MyProject.vue
  src/views/member/MyScrap.vue
Labels: 🍀 enhancement, ✨ feature

#32 chore: 이미지 변수 수정
  src/views/LaunchedProject/LaunchedProjectEdit.vue
  src/views/LaunchedProject/LaunchedProjectRegister.vue
Labels: 🚧 fix

#33 feat/IS-82: 마이페이지, 프로젝트 관리 페이지, 채팅 페이지 디자인 수정
  src/components/card/EnChatroomComponent.vue
  src/components/card/EnChattingListComponent.vue
  src/components/card/ProjectApplyComponent.vue
  src/components/card/ProjectManagementComponent.vue
  src/components/card/ProjectScrapComponent.vue
  src/components/chip/BasicChip.vue
  src/components/header/HeaderComponent.vue
  src/router/memberRouter.js
  src/views/member/ApplyList.vue
  src/views/member/ApplyManagement.vue
  src/views/member/ChatroomView.vue
  src/views/member/ChattingList.vue
  src/views/member/EmailUpdate.vue
  src/views/member/MyApply.vue
  src/views/member/MyPage.vue
  src/views/member/MyPageEdit.vue
  src/views/member/MyProject.vue
  src/views/member/MyScrap.vue
Labels: 🍀 enhancement, ✨ feature

#34 Feat/IS -74 : 완성된프로젝트 detail 화면
  src/components/chip/MemberChip.vue
  src/data/smallChat.js
  src/router/LaunchedProjectRouter.js
  src/views/LaunchedProject/LaunchedProjectDetail.vue
  src/views/LaunchedProject/LaunchedProjectList.vue
Labels: ✨ feature, 🚧 fix

#45 fix: 알림 디자인, 스크랩 페이지, 프로젝트 지원 내역 리뷰 사항 반영
  src/components/card/ProjectApplyComponent.vue
  src/components/card/ProjectManagementComponent.vue
  src/components/card/ProjectScrapComponent.vue
  src/components/header/HeaderComponent.vue
  src/views/member/ApplyManagement.vue
  src/views/member/MyScrap.vue
Labels: 🍀 enhancement

#56 fix/IS-114: 알림 부분 수정
  src/components/header/HeaderComponent.vue
  src/views/member/MyAlert.vue
Labels: 🚧 fix

#83 fix/IS-137 : project view 코드 수정 & 프로젝트 및 완성된 프로젝트 주석 제거
  src/router/projectRouter.js
  src/views/LaunchedProject/LaunchedProjectEdit.vue
  src/views/LaunchedProject/LaunchedProjectList.vue
  src/views/LaunchedProject/LaunchedProjectRegister.vue
  src/views/project/ProjectCreate2.vue
  src/views/project/ProjectEdit2.vue
  src/views/project/ProjectView.vue
Labels: 🚧 fix
